
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri May 09 11:42:34 EDT 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class TokenIds {
  /* terminals */
  public static final int TEMPOINTCONST = 23;
  public static final int PHRASE = 4;
  public static final int STRING_CONST = 22;
  public static final int SONG = 3;
  public static final int VOLUMEWORD = 21;
  public static final int RBRACE = 13;
  public static final int OCTAVE = 6;
  public static final int RPAREN = 11;
  public static final int SEMI = 15;
  public static final int INSTRUMENT = 17;
  public static final int TEMPO = 18;
  public static final int VOLUME = 16;
  public static final int LPAREN = 10;
  public static final int LBRACE = 12;
  public static final int NOTE = 5;
  public static final int EOF = 0;
  public static final int OCTAVEINTCONST = 19;
  public static final int LENGTH = 8;
  public static final int LEX_ERROR = 2;
  public static final int error = 1;
  public static final int OCTAVEMODVAL = 20;
  public static final int REST = 7;
  public static final int ACCIDENTAL = 9;
  public static final int REPEAT = 14;
}

